Feature/#5 Category CUD구현
prgrms-web-devcourse/Team_Ahpuh_Surf_BE pull request #8
Opened 2021-12-05 10:39 UTC by suebeen

## 📄 Description

- close : #5 

> 카테고리 CUD
user구현 전이라 우선 전체 조회 부분 제외하고 구현했습니다.
categoryServiceTest 를 위해 user, post부분은 주석처리했어요!
## 📌 구현 내용

- [ ] 카테고리 수정
- [ ] 카테고리 수정
- [ ] 카테고리 삭제

## ✅ PR 포인트

- baseEntity에서 오류나서 <LocalDateTime> 삭제하고 is_deleted에 @Builder.default 추가했습니다!
- 그리고 softDelete라서 delete시에 is_deleted = true로 변경하고 db에서 삭제안하는게 맞나요? 🤔
- test코드 작성하실때 다들 어떻게 하시나요? 저는 SpringBootTest사용했습니다!

2021-12-05 12:00 UTC, cse0518 commented
오 수고하셨습니다!! 👍👍

저도 isDeleted 수정해야 될 것 같았는데 감사해요!!
근데 혹시 baseEntity랑 Category 엔티티에 SuperBuilder 빼도 정상 작동 되나요??

삭제 시 softDelete로 db 삭제는 안하고 true로만 변경 맞아용!
테스트 코드 보니까 잘 설정하신것 같습니다!

테스트 코드는 저도 SpringBootTest로 하려구요!

2021-12-05 12:04 UTC, cse0518 commented
아 그리고 baseEntity에 isDeleted setter가 있는데
혹시 동작이 안되나요??

2021-12-05 12:06 UTC, suebeen commented
> 오 수고하셨습니다!! 👍👍
> 
> 저도 isDeleted 수정해야 될 것 같았는데 감사해요!! 근데 혹시 baseEntity랑 Category 엔티티에 SuperBuilder 빼도 정상 작동 되나요??
> 
> 삭제 시 softDelete로 db 삭제는 안하고 true로만 변경 맞아용! 테스트 코드 보니까 잘 설정하신것 같습니다!
> 
> 테스트 코드는 저도 SpringBootTest로 하려구요!



> 오 수고하셨습니다!! 👍👍
> 
> 저도 isDeleted 수정해야 될 것 같았는데 감사해요!! 근데 혹시 baseEntity랑 Category 엔티티에 SuperBuilder 빼도 정상 작동 되나요??
> 
> 삭제 시 softDelete로 db 삭제는 안하고 true로만 변경 맞아용! 테스트 코드 보니까 잘 설정하신것 같습니다!
> 
> 테스트 코드는 저도 SpringBootTest로 하려구요!

SuperBuilder빼면 에러나요!

2021-12-05 12:09 UTC, suebeen commented
> 오 수고하셨습니다!! 👍👍
> 
> 저도 isDeleted 수정해야 될 것 같았는데 감사해요!! 근데 혹시 baseEntity랑 Category 엔티티에 SuperBuilder 빼도 정상 작동 되나요??
> 
> 삭제 시 softDelete로 db 삭제는 안하고 true로만 변경 맞아용! 테스트 코드 보니까 잘 설정하신것 같습니다!
> 
> 테스트 코드는 저도 SpringBootTest로 하려구요!

SuperBuilder빼면 에러나요!
setIsDeleted는 작동잘됩니당 👍

2021-12-05 12:13 UTC, cse0518 commented
> SuperBuilder빼면 에러나요!
> setIsDeleted는 작동잘됩니당 👍

아하! 알겠습니다~ 수고하셨어용!!
저도 조만간 PR 날립니다~

2021-12-05 12:18 UTC, cse0518 commented
아아.. 나눠서 계속 댓글 달아서 죄송한데..
`@NoArgsConstructor` 를 생성못하게 하는게 좋지 않을까요??

저는 `@NoArgsConstructor(access = AccessLevel.PRIVATE)` 이렇게 하려고 하거든요!
PRIVATE가 안되는 상황엔 PROTECTED로 하려구요!

2021-12-05 14:02 UTC, suebeen commented
> 아아.. 나눠서 계속 댓글 달아서 죄송한데.. `@NoArgsConstructor` 를 생성못하게 하는게 좋지 않을까요??
> 
> 저는 `@NoArgsConstructor(access = AccessLevel.PRIVATE)` 이렇게 하려고 하거든요! PRIVATE가 안되는 상황엔 PROTECTED로 하려구요!

오호 월요일에 머지할때 수정할께요~ 코드부분에 편하게 코멘트달아주세요! ㅋㅋㅋㅋ

2021-12-06 06:37 UTC, Jummi10 requested changes
수고하셨습니다 수빈님!! 저는 유닛 테스트 관련해서 SpringBootTest 말고 다르게 했는데 코멘트로 따로 남길게요

2021-12-06 06:37 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/common/exception/EntityExceptionSuppliers.java
> +        throw new IllegalArgumentException("Category with given id not found.");
`given id`가 정확히 무엇인지까지도 적어주면 더 구체적인 에러 메세지가 될 것 같아요
간단히 예를 들면 "Category with given id not found. category id is " + categoryId 이런 식으로요!

2021-12-06 06:37 UTC, Jummi10 commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +    }
assertAll()로 묶어서 검증을 해주면 3번째에서 테스트 실패를 해도 4,5번째 줄이 테스트를 통과하는지 확인할 수 있습니다

2021-12-06 06:37 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/category/repository/CategoryRepository.java
> +@Repository
JpaRepository를 상속한 인터페이스에는 @Respository를 반드시 붙여주지 않아도 되는 걸로 알고 있습니다!

2021-12-06 06:37 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +    private Long id;
erd 보면 이 컬럼 이름이 `category_id`로 되어있더라구요 여기도 @Column 넣어주면 될 것 같아요

2021-12-06 06:37 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/category/service/CategoryServiceImpl.java
> +    }
저는 요청을 컨트롤러단에서 받고 처리해서 데이터를 인자로 하나씩 서비스로 내려주게끔 했는데 dto 전체를 다 내려주셨군요! 저희끼리 이 부분에 대해서도 얘기해보면 좋을 것 같아요 ㅎㅎ

2021-12-06 06:37 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
오 서비스를 왜 인터페이스로 분리하셨나요! 그냥 궁금해서,,

2021-12-06 06:37 UTC, Jummi10 commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +
서비스에서 예외 던지는 부분도 잘 되는지 테스트해보면 좋을 것 같습니다!

2021-12-06 06:44 UTC, cse0518 commented on src/main/java/org/ahpuh/backend/common/exception/EntityExceptionSuppliers.java
> +        throw new IllegalArgumentException("Category with given id not found.");
new UsernameNotFoundException("Could not found user for " + email));

저는 이런식으로 작성했습니다!

2021-12-06 06:51 UTC, cse0518 commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
- 저번에 저도 찾아보고 정리했었는데 첨부할게요!

![image](https://user-images.githubusercontent.com/60170616/144800679-152fe333-c32a-4cfe-95a0-a69e691e6fa8.png)

2021-12-06 06:53 UTC, suebeen commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +
넵 우선 기본적인 것만 테스트하고 추후에 테스트는 더 추가하려구요!

2021-12-06 06:54 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
이것도 다들 인터페이스안하셨으면 지우겠습니다! 그냥 생각나는거 써놓고 구현하려다보니 인터페이스를 따로 분리했습니당

2021-12-06 06:55 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/service/CategoryServiceImpl.java
> +    }
네네 얘기해보고 정하는게 좋을거같아요!

2021-12-06 06:55 UTC, Jummi10 commented
@suebeen @cse0518 

유닛 테스트를 작성할 때에는 `@SpringBootTest`로 전체 스프링 부트를 띄우게끔 하지 않고 가볍게 테스트하려고 이것저것 찾아보면서 적용해봤었는데요

## Repository
`@DataJpaTest` + `@TestEntityManager`
Spring data Jpa 테스트할 때 사용
인메모리 디비 생성해서 entity들만 스캔, 테스트 후 자동 롤백
  
## Service
`@ExtendWith(MockitoExtension.class)` + `@Mock` + `@InjectMocks`
@Mock: mocking할 repository
@InjectMocks: 모킹한 객체를 사용할 객체 - service

## Controller
`@WebMvcTest(ProductOptionController.class)` + `MockMvc` + RestDocs
Web 관련된 설정과 클래스들만 컨텍스트로 띄워주는 기능

## 통합 테스트
`@SpringBootTest` + `TestRestTemplate`
전체 컨텍스트를 띄워서 클라이언트에서 요청을 보내듯이 테스트해볼 수 있음

각각 자세한 내용들은 아래 참고 자료들 보시면 상세하게 설명되어있습니다! 첫번째 참고 영상이 스프링에서 올려준 영상이라서 이걸 위주로 참고했고 다른 방법들도 있는것 같아요
저는 저번 프로젝트하면서 공부하는 김에 테스트 공부도 좀 제대로 해보자 해서 이렇게 해보았던거고 일단 공유드리는건데, 사실 너무 과하다 싶으면 원래 하던대로 하셔도 괜찮을 것 같습니다~

### 참고 자료
- [Test Driven Development with Spring Boot - Sannidhi Jalukar, Madhura Bhave](https://www.youtube.com/watch?v=s9vt6UJiHg4)
- [NHN Cloud Meetup - Spring Boot Test 어노테이션 정리](https://meetup.toast.com/posts/124)

2021-12-06 06:56 UTC, suebeen commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +    }
오 수정하겠습니다!

2021-12-06 07:48 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/common/exception/EntityExceptionSuppliers.java
> +        throw new IllegalArgumentException("Category with given id not found.");
저도 `NotFoundException`라고 IllegalArgumentException 상속받는 예외 클래스 하나 따로 만들어서 했는데 수빈님 방법처럼 명시적으로 해도 좋을 것 같아요 근데 하나로 통일은 필요할 것 같네요!

2021-12-06 08:10 UTC, Jummi10 commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
오호 아닙니다 저도 인터페이스 분리해서 한 번 개발해볼게요!

2021-12-07 01:03 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/converter/CategoryConverter.java
> +    public Category toEntity(CategoryCreateRequestDto dto) {
dto라는 단어보다 좀 더 직관적인 명명을 짓는게 어떤까요?

2021-12-07 01:04 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
> +    private boolean isPublic = true;
default값이 ture로 정해지는데 Dto에서 처리할 이유가 있나요?

2021-12-07 01:04 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/dto/CategoryUpdateRequestDto.java
> +    @NotBlank
이름에 대한 길이 규칙은 없나요?

2021-12-07 01:06 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +    private int averageScore;
평균점수인데 int로 해도 되나요?

2021-12-07 01:06 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +        this.setIsDeleted(true);
setter를 사용하지 말고 이 내부에서 deleted를 ture로 변경하는게 어떤까요?

2021-12-07 01:08 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
인터페이스 분리에 관련해서 위와 같은 장점이 있지만, 단점도 존재하는데 단점도 알려주세요~

2021-12-07 01:09 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/service/CategoryServiceImpl.java
> +    }
한줄로 적는게 좋을수도 잇지만, 지금와 같이 보면 가독성이 떨어질수 있어요.

2021-12-07 01:10 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/common/entity/BaseEntity.java
> +    @Builder.Default private Boolean isDeleted = false;
```suggestion
    @Builder.Default 
    private Boolean isDeleted = false;
```

2021-12-07 01:10 UTC, ksy90101 commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +@SpringBootTest
서비스 테스트를 SpringBootTest로 하신 이유가 있나요?

2021-12-07 01:11 UTC, ksy90101 commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +        assertThat(categoryRepository.findAll().size(), is(1));
삭제된건 실제 삭제된거라서 size도 0이 나오는게 정상일거 같아요.

2021-12-07 03:37 UTC, cse0518 commented on src/main/java/org/ahpuh/backend/category/service/CategoryService.java
> +public interface CategoryService {
단점을 꼽자면 대부분의 프로젝트에서 Service 구현체를 하나만 만들고 사용해서 실질적으로 인터페이스를 사용하는 것에 대한 이점을 가져가지 못하고, 관습적으로 추상화 패턴을 적용하고 있습니다! 이로인해 설계만 좀 더 복잡해지게 됩니다.

Spring AOP가 예전에는 JDK Dynamic Proxy를 사용했는데 인터페이스 명세 기반으로 프록시를 지원해서 이런 관습이 생겼고, 현재는 `CGLIB Proxy`를 기본으로 사용해서 인터페이스를 명세하지 않아도 된다고 합니다.

Service 인터페이스를 활용해볼만한 상황은 MemberService 인터페이스의 구현체로 UserService, AdminService 등으로 나누어 사용하는 정도가 있을 것 같습니다!
우리 프로젝트에서는 굳이 관습적으로 안써도 되긴 하겠네요. 통일하면 될 것 같습니다!

2021-12-07 06:13 UTC, merged

2021-12-07 06:24 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/converter/CategoryConverter.java
> +    public Category toEntity(CategoryCreateRequestDto dto) {
createRequest 이런식으로 수정하겠습니다!

2021-12-07 06:29 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/dto/CategoryUpdateRequestDto.java
> +    @NotBlank
카테고리 이름뒤에 이모티콘도 같이 붙여서 주신다고해서 이부분은 일단 규칙 설정을 안했어요! 프론트분들과 얘기하고 정해야할 것 같습니당

2021-12-07 06:30 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +    private int averageScore;
소수점은 쓸일이 없을거같아서 int로 설정했는데 아마 내려서 저장할거같습니다!

2021-12-07 06:31 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +        this.setIsDeleted(true);
이 메서드는 삭제하고 service안에서 처리하도록 수정하겠습니다!

2021-12-07 06:33 UTC, suebeen commented on src/main/java/org/ahpuh/backend/common/entity/BaseEntity.java
> +    @Builder.Default private Boolean isDeleted = false;
머지후에 수정하도록 하겠습니다!!

2021-12-07 06:34 UTC, suebeen commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +@SpringBootTest
mock객체를 활용한 테스트보다는 직접 SpringBootTest로 확인해보고싶어서 사용했습니다!

2021-12-07 06:34 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +        this.setIsDeleted(true);
제가 생각해보니, 부모 메서드를 사용하는거 같은데, 부모 메서드를 사용한다는걸 명시 하면 어떨까요?

2021-12-07 06:35 UTC, suebeen commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +        assertThat(categoryRepository.findAll().size(), is(1));
앗... 그러네요.... SoftDelete어노테이션을 만들어서 사용했는데 이건 한번 확인해보고 수정하겠습니당

2021-12-07 06:35 UTC, ksy90101 commented on src/test/java/org/ahpuh/backend/category/service/CategoryServiceTest.java
> +@SpringBootTest
모든 테스트를 @SpringBootTest로 하면 테스트 전체 돌릴때 속도가 많이 느릴꺼에요.
빠르게 확인을 할수가 없죠.
따라서 단위테스트로 작성할부분들은 작성하고 통합테스트가 있는거에요~
지금 방법이 틀렸다는건 아니지만 고민해보시면 좋을거 같아요.

2021-12-07 06:43 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
> +    private boolean isPublic = true;
카테고리를 생성할때 isPublic에 대한 정보는 받지 않아서 default를 true로 만들었습니다

2021-12-07 06:44 UTC, ksy90101 commented on src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
> +    private boolean isPublic = true;
정보를 받지 않는건데 Dto에 값이 있을 필요가 있나요?

2021-12-07 08:08 UTC, cse0518 commented on src/main/java/org/ahpuh/backend/category/entity/Category.java
> +        this.setIsDeleted(true);
부모 엔티티에 delete 메소드 하나로 통일하고 엔티티에서는 메소드를 삭제했는데,
부모 메소드를 사용한다는 걸 명시하는게 주석 말씀하시는 건가요..??

2021-12-07 08:12 UTC, cse0518 commented on src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
> +    private boolean isPublic = true;
아아 dto 안에 isPublic 필드를 삭제하고,
엔티티를 만든 후에 isPublic을 true로 설정하는게 더 나아보입니다!
엔티티에서 isPublic 필드를 default = true로 설정해도되구요!

2021-12-08 18:37 UTC, suebeen commented on src/main/java/org/ahpuh/backend/category/dto/CategoryCreateRequestDto.java
> +    private boolean isPublic = true;
엔티티에서 default값을 true로 하도록 수정했습니다!